# template.yaml

---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          ports:
            - containerPort: {{ .Values.mongo.port }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongo.username }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongo.password }}
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongo.database }}

---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-mongo
  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}

---
# Mongo Express Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo-express
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo-express
    spec:
      containers:
        - name: mongo-express
          image: {{ .Values.mongoExpress.image }}
          ports:
            - containerPort: {{ .Values.mongoExpress.port }}
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: {{ .Values.mongo.username }}
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: {{ .Values.mongo.password }}
            - name: ME_CONFIG_MONGODB_SERVER
              value: {{ .Release.Name }}-mongo-service

---
# Mongo Express Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-express-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-mongo-express
  ports:
    - port: {{ .Values.mongoExpress.port }}
      targetPort: {{ .Values.mongoExpress.port }}

---
# Ingress (optional)
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-mongo-express-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-mongo-express-service
                port:
                  number: {{ .Values.mongoExpress.port }}
{{- end }}